
#mysql pass=moreCoffee
#       port=3360
spring:
  jpa:
    hibernate.ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/ridesocial
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    azure:
      storage:
        blob:
          account-name: ${accountName}
          account-key: ${key}
          endpoint: ${blobEndpoint}